
name: Build GH Pages - Manual

on: workflow_dispatch


jobs:
  upload-gh-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${ hashFiles('setup.py') }-${ hashFiles('dev-requirements.txt') }

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Run - Upload GH Pages
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/cbsl/gh_pages/build.py

    - name: Checkout repo branch gh-pages
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy gh-pages, and push to repo branch gh-pages
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp -r /tmp/cbsl/gh-pages/* .
        echo "* $(date)" >> update.log
        git add .
        git commit -m "Updated gh-pages $(date)"
        git push origin gh-pages
